# Generated by Django 5.2.11 on 2026-04-26 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacherprofile_phone_teacherprofile_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('submission_type', models.CharField(choices=[('file', 'Файл або фото'), ('text', 'Текст у платформі'), ('link', 'Посилання'), ('any', 'Файл або текст')], default='any', max_length=20)),
                ('material_file', models.FileField(blank=True, null=True, upload_to='homework/materials/')),
                ('material_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Активне'), ('closed', 'Закрите')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_homeworks', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_homeworks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('file_answer', models.FileField(blank=True, null=True, upload_to='homework/submissions/')),
                ('link_answer', models.URLField(blank=True)),
                ('student_comment', models.TextField(blank=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Здано'), ('reviewed', 'Перевірено'), ('redo', 'На доопрацювання')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='core.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
