# Generated by Django 5.2.11 on 2026-04-27 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homework_homeworksubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='material_file',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='material_link',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='submission_type',
        ),
        migrations.AddField(
            model_name='homework',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to='homework_answers/'),
        ),
        migrations.AddField(
            model_name='homework',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='core.calendarevent'),
        ),
        migrations.AddField(
            model_name='homework',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('assigned', 'Призначено'), ('submitted', 'Здано'), ('checked', 'Перевірено'), ('late', 'Прострочено')], default='assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_homeworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(default='Домашнє завдання', max_length=200),
        ),
        migrations.DeleteModel(
            name='HomeworkSubmission',
        ),
    ]
