# Generated by Django 5.2.11 on 2026-04-30 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_homework_material_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='answer_file',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='homework',
            name='allow_file_answer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='allow_late_submission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='allow_text_answer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homework',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='core.calendarevent'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='HomeworkMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='homework_materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.homework')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='core.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkSubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='homework_answers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.homeworksubmission')),
            ],
        ),
    ]
