# Generated by Django 5.2.11 on 2026-05-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_homeworksubmission_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='is_synced_with_google',
            field=models.BooleanField(default=False),
        ),
    ]
