# Generated by Django 5.2.11 on 2026-05-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='reminder_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homework',
            name='reminder_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
