# Generated by Django 5.2.11 on 2026-05-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_conversation_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lesson_created', 'Створено урок'), ('homework_created', 'Створено домашнє завдання'), ('homework_submitted', 'Домашнє завдання здано'), ('homework_checked', 'Домашнє завдання перевірено'), ('message', 'Нове повідомлення')], max_length=30),
        ),
    ]
