# Generated by Django 5.2.11 on 2026-05-10 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='core.calendarevent'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текст'), ('lesson_reschedule_request', 'Запит на перенесення'), ('lesson_cancelled', 'Урок скасовано'), ('lesson_reschedule_accepted', 'Перенесення прийнято'), ('lesson_reschedule_declined', 'Перенесення відхилено'), ('lesson_reschedule_counter', 'Запропоновано інший час')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lesson_created', 'Створено урок'), ('homework_created', 'Створено домашнє завдання'), ('homework_submitted', 'Домашнє завдання здано'), ('homework_checked', 'Домашнє завдання перевірено'), ('message', 'Нове повідомлення'), ('lesson_rescheduled', 'Урок перенесено'), ('lesson_cancelled', 'Урок скасовано')], max_length=30),
        ),
        migrations.CreateModel(
            name='LessonChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('reschedule', 'Перенесення'), ('cancel', 'Скасування')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Очікує відповіді'), ('accepted', 'Прийнято'), ('declined', 'Відхилено'), ('countered', 'Запропоновано інший час'), ('cancelled', 'Скасовано')], default='pending', max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('old_start_time', models.DateTimeField()),
                ('old_end_time', models.DateTimeField(blank=True, null=True)),
                ('proposed_start_time', models.DateTimeField(blank=True, null=True)),
                ('proposed_end_time', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_requests', to='core.conversation')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='core.calendarevent')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_change_requests', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_lesson_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='change_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='core.lessonchangerequest'),
        ),
    ]
