from django.urls import path
from . import views
from .views import (

    student_dashboard_view,

)
urlpatterns = [
    #path("dashboard/", dashboard_view, name="dashboard"),
    path("teachers/", views.teachers, name="teachers"),
    path("dashboard/student/", student_dashboard_view, name="student_dashboard"),
    path("teacher/", views.teacher_dashboard, name="teacher_dashboard"),
    path("calendar/", views.calendar_view, name="calendar"),
    path("teacher/profile/", views.teacher_profile, name="teacher_profile"),
    path("lesson/new/", views.create_lesson, name="create_lesson"),
    path("lessons/", views.lessons_view, name="lessons"),
    path("calendar/<int:year>/<int:month>/<int:day>/", views.calendar_day, name="calendar_day"),
    path("teacher/add-student/", views.add_student_manual, name="add_student_manual"),
    path("teacher/generate-code/", views.generate_teacher_code, name="generate_teacher_code"),
    path("lesson/<int:lesson_id>/", views.lesson_detail, name="lesson_detail"),
    path("lesson/<int:lesson_id>/edit/", views.create_lesson, name="edit_lesson"),
    path("student/profile/", views.student_profile, name="student_profile"),
    path("homework/", views.homework, name="homework"),
    path("homework/new/", views.create_homework, name="create_homework"),
    path("homework/<int:pk>/", views.homework_detail, name="homework_detail"),
    path("homework/<int:pk>/delete/", views.delete_homework, name="delete_homework"),
    path("homework/create/", views.create_homework, name="create_homework"),
    path("homework/<int:pk>/edit/", views.create_homework, name="edit_homework"),
    path("teacher/<int:teacher_id>/profile/", views.teacher_public_profile, name="teacher_public_profile"),
    path("student/<int:student_id>/profile/", views.student_public_profile, name="student_public_profile"),
    path("", views.home, name="home"),
    path("landing/", views.landing, name="landing"),
    path("google/connect/", views.google_calendar_auth, name="google_calendar_auth"),
    path("google/callback/", views.google_calendar_callback, name="google_calendar_callback"),
    path("teacher/statistics/", views.teacher_statistics, name="teacher_statistics"),
    path("student/statistics/", views.student_statistics, name="student_statistics"),
    path("notifications/", views.notifications_view, name="notifications"),
    path("api/notifications/list/", views.unread_notifications_api, name="unread_notifications_api"),
    path("api/notifications/unread/", views.unread_notifications, name="unread_notifications"),
    path("api/notifications/read/<int:pk>/", views.mark_notification_read, name="mark_notification_read"),
    path("notifications/", views.notifications_view, name="notifications"),
    path("notifications/<int:pk>/read/", views.mark_notification_read, name="mark_notification_read"),
    path("notifications/read-all/", views.mark_all_notifications_read, name="mark_all_notifications_read"),
    path("messages/", views.chat_view, name="chat"),
    path("messages/<int:conversation_id>/", views.chat_view, name="chat_detail"),
    path("messages/<int:conversation_id>/send/", views.send_chat_message, name="send_chat_message"),
    path("lesson/<int:lesson_id>/reschedule/", views.request_lesson_reschedule, name="request_lesson_reschedule"),
    path("lesson/<int:lesson_id>/cancel/", views.cancel_lesson_request, name="cancel_lesson_request"),
    path("lesson-request/<int:request_id>/accept/", views.accept_reschedule_request, name="accept_reschedule_request"),
    path("lesson-request/<int:request_id>/decline/", views.decline_reschedule_request, name="decline_reschedule_request"),
    path("lesson-request/<int:request_id>/counter/", views.counter_reschedule_request, name="counter_reschedule_request"),
    path("students/", views.students, name="students"),
    path("chat/student/<int:student_id>/",  views.start_chat_with_student, name="start_chat_with_student"),
    path("chat/teacher/<int:teacher_id>/", views.start_chat_with_teacher, name="start_chat_with_teacher"),
    path("lesson/<int:lesson_id>/feedback/", views.submit_lesson_feedback, name="submit_lesson_feedback"),
    path("student/achievements/", views.student_achievements, name="student_achievements"),
]


